//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBInStudioServer.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DBInStudioServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add tag to database 的本地化字符串。
        /// </summary>
        internal static string AddTagHlp {
            get {
                return ResourceManager.GetString("AddTagHlp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 press &apos;enter&apos; to exit. 的本地化字符串。
        /// </summary>
        internal static string AnyKeyToExit {
            get {
                return ResourceManager.GetString("AnyKeyToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit? input &apos;y&apos; to exit,anyother char for cancel. 的本地化字符串。
        /// </summary>
        internal static string AppExitHlp {
            get {
                return ResourceManager.GetString("AppExitHlp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear all tags from database 的本地化字符串。
        /// </summary>
        internal static string ClearTagHlp {
            get {
                return ResourceManager.GetString("ClearTagHlp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 database &apos;{0}&apos; is already in running 的本地化字符串。
        /// </summary>
        internal static string databaseinrunningHlp {
            get {
                return ResourceManager.GetString("databaseinrunningHlp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invailed Parameter! 的本地化字符串。
        /// </summary>
        internal static string ErroParameter {
            get {
                return ResourceManager.GetString("ErroParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 exit 的本地化字符串。
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit database manager and back to parent 的本地化字符串。
        /// </summary>
        internal static string ExitDatabaseHlp {
            get {
                return ResourceManager.GetString("ExitDatabaseHlp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export tags to a csv file 的本地化字符串。
        /// </summary>
        internal static string ExportHlp {
            get {
                return ResourceManager.GetString("ExportHlp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 manage or create a database 的本地化字符串。
        /// </summary>
        internal static string GDMsgHlp {
            get {
                return ResourceManager.GetString("GDMsgHlp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 enter h for command help information 的本地化字符串。
        /// </summary>
        internal static string HelpMsg {
            get {
                return ResourceManager.GetString("HelpMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 display command list 的本地化字符串。
        /// </summary>
        internal static string HMsg {
            get {
                return ResourceManager.GetString("HMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import tags from a csv file 的本地化字符串。
        /// </summary>
        internal static string ImportHlp {
            get {
                return ResourceManager.GetString("ImportHlp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List all exist database 的本地化字符串。
        /// </summary>
        internal static string ListDatabaseHlp {
            get {
                return ResourceManager.GetString("ListDatabaseHlp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List the summary info of a specical type tags or all tags 的本地化字符串。
        /// </summary>
        internal static string ListTagHlp {
            get {
                return ResourceManager.GetString("ListTagHlp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will create database &apos;{0}&apos;? Input &apos;y&apos; for sure ,anyother char for cancel. 的本地化字符串。
        /// </summary>
        internal static string NewDatabase {
            get {
                return ResourceManager.GetString("NewDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quickly generate the specified number of tags for test purposes 的本地化字符串。
        /// </summary>
        internal static string QuickGeneraterTagHlp {
            get {
                return ResourceManager.GetString("QuickGeneraterTagHlp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove a tag from database 的本地化字符串。
        /// </summary>
        internal static string RemoveTagHlp {
            get {
                return ResourceManager.GetString("RemoveTagHlp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rerun database ‘{0}’ failed. 的本地化字符串。
        /// </summary>
        internal static string Rerundatabasefail {
            get {
                return ResourceManager.GetString("Rerundatabasefail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rerun database ‘{0}’ sucessfull. 的本地化字符串。
        /// </summary>
        internal static string RerundatabaseSucessful {
            get {
                return ResourceManager.GetString("RerundatabaseSucessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restart current database 的本地化字符串。
        /// </summary>
        internal static string ReStartDatabaseHlp {
            get {
                return ResourceManager.GetString("ReStartDatabaseHlp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save database 的本地化字符串。
        /// </summary>
        internal static string SaveDatabaseHlp {
            get {
                return ResourceManager.GetString("SaveDatabaseHlp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start current database 的本地化字符串。
        /// </summary>
        internal static string StartDatabaseHlp {
            get {
                return ResourceManager.GetString("StartDatabaseHlp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop database ‘{0}’ failed. 的本地化字符串。
        /// </summary>
        internal static string Stopdatabasefail {
            get {
                return ResourceManager.GetString("Stopdatabasefail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop database 的本地化字符串。
        /// </summary>
        internal static string StopDatabaseHlp {
            get {
                return ResourceManager.GetString("StopDatabaseHlp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop database ‘{0}’ sucessfull. 的本地化字符串。
        /// </summary>
        internal static string StopdatabaseSucessful {
            get {
                return ResourceManager.GetString("StopdatabaseSucessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}  {1} Tag 的本地化字符串。
        /// </summary>
        internal static string TagMsg {
            get {
                return ResourceManager.GetString("TagMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify the value of a property by a tag 的本地化字符串。
        /// </summary>
        internal static string UpdateTagHlp {
            get {
                return ResourceManager.GetString("UpdateTagHlp", resourceCulture);
            }
        }
    }
}
