//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBInStudio.Desktop.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DBInStudio.Desktop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Value 的本地化字符串。
        /// </summary>
        internal static string AbsoluteValue {
            get {
                return ResourceManager.GetString("AbsoluteValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add tag {0} failed! 的本地化字符串。
        /// </summary>
        internal static string AddTagFail {
            get {
                return ResourceManager.GetString("AddTagFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All group 的本地化字符串。
        /// </summary>
        internal static string AllGroup {
            get {
                return ResourceManager.GetString("AllGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Append 的本地化字符串。
        /// </summary>
        internal static string Append {
            get {
                return ResourceManager.GetString("Append", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Circle 的本地化字符串。
        /// </summary>
        internal static string Circle {
            get {
                return ResourceManager.GetString("Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CompressType 的本地化字符串。
        /// </summary>
        internal static string CompressType {
            get {
                return ResourceManager.GetString("CompressType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert 的本地化字符串。
        /// </summary>
        internal static string Convert {
            get {
                return ResourceManager.GetString("Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database 的本地化字符串。
        /// </summary>
        internal static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database select 的本地化字符串。
        /// </summary>
        internal static string databaseSelect {
            get {
                return ResourceManager.GetString("databaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dead zone 的本地化字符串。
        /// </summary>
        internal static string DeadAreaCompress {
            get {
                return ResourceManager.GetString("DeadAreaCompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        internal static string DeadAreaType {
            get {
                return ResourceManager.GetString("DeadAreaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dead zone 的本地化字符串。
        /// </summary>
        internal static string DeadAreaValue {
            get {
                return ResourceManager.GetString("DeadAreaValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        internal static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Driver 的本地化字符串。
        /// </summary>
        internal static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EnableWrite 的本地化字符串。
        /// </summary>
        internal static string EnableWrite {
            get {
                return ResourceManager.GetString("EnableWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 erro 的本地化字符串。
        /// </summary>
        internal static string erro {
            get {
                return ResourceManager.GetString("erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conversion formula 的本地化字符串。
        /// </summary>
        internal static string funTitle {
            get {
                return ResourceManager.GetString("funTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group 的本地化字符串。
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Id 的本地化字符串。
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Some erro has happened,do you see erro.txt for detail? 的本地化字符串。
        /// </summary>
        internal static string ImportErroMsg {
            get {
                return ResourceManager.GetString("ImportErroMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import mode 的本地化字符串。
        /// </summary>
        internal static string ImportMode {
            get {
                return ResourceManager.GetString("ImportMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Admin 的本地化字符串。
        /// </summary>
        internal static string IsAdmin {
            get {
                return ResourceManager.GetString("IsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Link 的本地化字符串。
        /// </summary>
        internal static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login Failed! 的本地化字符串。
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logout 的本地化字符串。
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lossless 的本地化字符串。
        /// </summary>
        internal static string LosslessCompress {
            get {
                return ResourceManager.GetString("LosslessCompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mars database developer 的本地化字符串。
        /// </summary>
        internal static string MainwindowTitle {
            get {
                return ResourceManager.GetString("MainwindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MaxValue 的本地化字符串。
        /// </summary>
        internal static string MaxValue {
            get {
                return ResourceManager.GetString("MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MinValue 的本地化字符串。
        /// </summary>
        internal static string MinValue {
            get {
                return ResourceManager.GetString("MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify 的本地化字符串。
        /// </summary>
        internal static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New database 的本地化字符串。
        /// </summary>
        internal static string NewDatabase {
            get {
                return ResourceManager.GetString("NewDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New database failed! 的本地化字符串。
        /// </summary>
        internal static string NewDatabaseFailed {
            get {
                return ResourceManager.GetString("NewDatabaseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        internal static string NoneCompress {
            get {
                return ResourceManager.GetString("NoneCompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password confirm 的本地化字符串。
        /// </summary>
        internal static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New password  的本地化字符串。
        /// </summary>
        internal static string PasswordNew {
            get {
                return ResourceManager.GetString("PasswordNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste 的本地化字符串。
        /// </summary>
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Percent 的本地化字符串。
        /// </summary>
        internal static string PercentValue {
            get {
                return ResourceManager.GetString("PercentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permission 的本地化字符串。
        /// </summary>
        internal static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permission list 的本地化字符串。
        /// </summary>
        internal static string PermissionList {
            get {
                return ResourceManager.GetString("PermissionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Precision 的本地化字符串。
        /// </summary>
        internal static string Precision {
            get {
                return ResourceManager.GetString("Precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read 的本地化字符串。
        /// </summary>
        internal static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReadWrite 的本地化字符串。
        /// </summary>
        internal static string ReadWrite {
            get {
                return ResourceManager.GetString("ReadWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReadWriteMode 的本地化字符串。
        /// </summary>
        internal static string ReadWriteMode {
            get {
                return ResourceManager.GetString("ReadWriteMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Record 的本地化字符串。
        /// </summary>
        internal static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RecordType 的本地化字符串。
        /// </summary>
        internal static string RecordType {
            get {
                return ResourceManager.GetString("RecordType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registor 的本地化字符串。
        /// </summary>
        internal static string Registor {
            get {
                return ResourceManager.GetString("Registor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReName 的本地化字符串。
        /// </summary>
        internal static string ReName {
            get {
                return ResourceManager.GetString("ReName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace 的本地化字符串。
        /// </summary>
        internal static string Replace {
            get {
                return ResourceManager.GetString("Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace all 的本地化字符串。
        /// </summary>
        internal static string ReplaceAll {
            get {
                return ResourceManager.GetString("ReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 save failed! 的本地化字符串。
        /// </summary>
        internal static string Savefailed {
            get {
                return ResourceManager.GetString("Savefailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 save sucessfull! 的本地化字符串。
        /// </summary>
        internal static string SaveSucessful {
            get {
                return ResourceManager.GetString("SaveSucessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Security 的本地化字符串。
        /// </summary>
        internal static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a database 的本地化字符串。
        /// </summary>
        internal static string SelectDatabase {
            get {
                return ResourceManager.GetString("SelectDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected group 的本地化字符串。
        /// </summary>
        internal static string SelectGroup {
            get {
                return ResourceManager.GetString("SelectGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server Ip 的本地化字符串。
        /// </summary>
        internal static string ServerIp {
            get {
                return ResourceManager.GetString("ServerIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ServerSecurity 的本地化字符串。
        /// </summary>
        internal static string ServerSecurity {
            get {
                return ResourceManager.GetString("ServerSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 set password fail. 的本地化字符串。
        /// </summary>
        internal static string SetPasswordfail {
            get {
                return ResourceManager.GetString("SetPasswordfail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 set password seccussfull. 的本地化字符串。
        /// </summary>
        internal static string SetPasswordSeccussful {
            get {
                return ResourceManager.GetString("SetPasswordSeccussful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slope zone 的本地化字符串。
        /// </summary>
        internal static string SlopeAreaValue {
            get {
                return ResourceManager.GetString("SlopeAreaValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slope 的本地化字符串。
        /// </summary>
        internal static string SlopeCompress {
            get {
                return ResourceManager.GetString("SlopeCompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch 的本地化字符串。
        /// </summary>
        internal static string Switch {
            get {
                return ResourceManager.GetString("Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tag 的本地化字符串。
        /// </summary>
        internal static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TagCount 的本地化字符串。
        /// </summary>
        internal static string TagCount {
            get {
                return ResourceManager.GetString("TagCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tag export complete! 的本地化字符串。
        /// </summary>
        internal static string TagExportComplete {
            get {
                return ResourceManager.GetString("TagExportComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TagGroup 的本地化字符串。
        /// </summary>
        internal static string TagGroup {
            get {
                return ResourceManager.GetString("TagGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update tag {0} failed! 的本地化字符串。
        /// </summary>
        internal static string UpdateTagFail {
            get {
                return ResourceManager.GetString("UpdateTagFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User 的本地化字符串。
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User list 的本地化字符串。
        /// </summary>
        internal static string UserList {
            get {
                return ResourceManager.GetString("UserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UserName 的本地化字符串。
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write 的本地化字符串。
        /// </summary>
        internal static string Write {
            get {
                return ResourceManager.GetString("Write", resourceCulture);
            }
        }
    }
}
