//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBInStudio.Desktop.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DBInStudio.Desktop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Value 的本地化字符串。
        /// </summary>
        internal static string AbsoluteValue {
            get {
                return ResourceManager.GetString("AbsoluteValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add tag {0} failed! 的本地化字符串。
        /// </summary>
        internal static string AddTagFail {
            get {
                return ResourceManager.GetString("AddTagFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All group 的本地化字符串。
        /// </summary>
        internal static string AllGroup {
            get {
                return ResourceManager.GetString("AllGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Append 的本地化字符串。
        /// </summary>
        internal static string Append {
            get {
                return ResourceManager.GetString("Append", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string CancelSave {
            get {
                return ResourceManager.GetString("CancelSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discard the content changed 的本地化字符串。
        /// </summary>
        internal static string CancelSave_Tooltip {
            get {
                return ResourceManager.GetString("CancelSave_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 you will be lost all data you have modify. To continue? 的本地化字符串。
        /// </summary>
        internal static string canceltosavemsg {
            get {
                return ResourceManager.GetString("canceltosavemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Circle 的本地化字符串。
        /// </summary>
        internal static string Circle {
            get {
                return ResourceManager.GetString("Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CompressType 的本地化字符串。
        /// </summary>
        internal static string CompressType {
            get {
                return ResourceManager.GetString("CompressType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert 的本地化字符串。
        /// </summary>
        internal static string Convert {
            get {
                return ResourceManager.GetString("Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom 的本地化字符串。
        /// </summary>
        internal static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Relative database path or absolute path 的本地化字符串。
        /// </summary>
        internal static string CustomDataPathTooltip {
            get {
                return ResourceManager.GetString("CustomDataPathTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database 的本地化字符串。
        /// </summary>
        internal static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database select 的本地化字符串。
        /// </summary>
        internal static string databaseSelect {
            get {
                return ResourceManager.GetString("databaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dead zone 的本地化字符串。
        /// </summary>
        internal static string DeadAreaCompress {
            get {
                return ResourceManager.GetString("DeadAreaCompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        internal static string DeadAreaType {
            get {
                return ResourceManager.GetString("DeadAreaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dead zone 的本地化字符串。
        /// </summary>
        internal static string DeadAreaValue {
            get {
                return ResourceManager.GetString("DeadAreaValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        internal static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Driver 的本地化字符串。
        /// </summary>
        internal static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EnableWrite 的本地化字符串。
        /// </summary>
        internal static string EnableWrite {
            get {
                return ResourceManager.GetString("EnableWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable double compression 的本地化字符串。
        /// </summary>
        internal static string EnableZipFile {
            get {
                return ResourceManager.GetString("EnableZipFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End port 的本地化字符串。
        /// </summary>
        internal static string EndPort {
            get {
                return ResourceManager.GetString("EndPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 erro 的本地化字符串。
        /// </summary>
        internal static string erro {
            get {
                return ResourceManager.GetString("erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset id 的本地化字符串。
        /// </summary>
        internal static string FindAvaiableId {
            get {
                return ResourceManager.GetString("FindAvaiableId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find the smallest unused ID and set it to the tag.The ID is used as the record identifier of historical records. Resetting the ID may cause confusion of historical data. 的本地化字符串。
        /// </summary>
        internal static string FindAvaiableIdTooltip {
            get {
                return ResourceManager.GetString("FindAvaiableIdTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conversion formula 的本地化字符串。
        /// </summary>
        internal static string funTitle {
            get {
                return ResourceManager.GetString("funTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group 的本地化字符串。
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Historical data retention time 的本地化字符串。
        /// </summary>
        internal static string HisDataKeepTime {
            get {
                return ResourceManager.GetString("HisDataKeepTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rerun database 的本地化字符串。
        /// </summary>
        internal static string HotReRun_Tooltip {
            get {
                return ResourceManager.GetString("HotReRun_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Id 的本地化字符串。
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start search ID 的本地化字符串。
        /// </summary>
        internal static string IDResetStartId {
            get {
                return ResourceManager.GetString("IDResetStartId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning: The ID is used as the record identifier of historical records. Resetting the ID may cause confusion of historical data. 的本地化字符串。
        /// </summary>
        internal static string IDResetWarnning {
            get {
                return ResourceManager.GetString("IDResetWarnning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Some erro has happened,do you see erro.txt for detail? 的本地化字符串。
        /// </summary>
        internal static string ImportErroMsg {
            get {
                return ResourceManager.GetString("ImportErroMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import mode 的本地化字符串。
        /// </summary>
        internal static string ImportMode {
            get {
                return ResourceManager.GetString("ImportMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Admin 的本地化字符串。
        /// </summary>
        internal static string IsAdmin {
            get {
                return ResourceManager.GetString("IsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Day) 的本地化字符串。
        /// </summary>
        internal static string KeepTimeUnit {
            get {
                return ResourceManager.GetString("KeepTimeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keyword 的本地化字符串。
        /// </summary>
        internal static string Keyword {
            get {
                return ResourceManager.GetString("Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Link 的本地化字符串。
        /// </summary>
        internal static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login Failed! 的本地化字符串。
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logout 的本地化字符串。
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lossless 的本地化字符串。
        /// </summary>
        internal static string LosslessCompress {
            get {
                return ResourceManager.GetString("LosslessCompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mars database developer 的本地化字符串。
        /// </summary>
        internal static string MainwindowTitle {
            get {
                return ResourceManager.GetString("MainwindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manual 的本地化字符串。
        /// </summary>
        internal static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome to Mars realtime iot database 的本地化字符串。
        /// </summary>
        internal static string MarsTitle {
            get {
                return ResourceManager.GetString("MarsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MaxValue 的本地化字符串。
        /// </summary>
        internal static string MaxValue {
            get {
                return ResourceManager.GetString("MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MaxValueCountPersecond 的本地化字符串。
        /// </summary>
        internal static string MaxValueCountPersecond {
            get {
                return ResourceManager.GetString("MaxValueCountPersecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MinValue 的本地化字符串。
        /// </summary>
        internal static string MinValue {
            get {
                return ResourceManager.GetString("MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify 的本地化字符串。
        /// </summary>
        internal static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New database 的本地化字符串。
        /// </summary>
        internal static string NewDatabase {
            get {
                return ResourceManager.GetString("NewDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New database failed! 的本地化字符串。
        /// </summary>
        internal static string NewDatabaseFailed {
            get {
                return ResourceManager.GetString("NewDatabaseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        internal static string NoneCompress {
            get {
                return ResourceManager.GetString("NoneCompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open database {0} failed! 的本地化字符串。
        /// </summary>
        internal static string opendatabasefailed {
            get {
                return ResourceManager.GetString("opendatabasefailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password confirm 的本地化字符串。
        /// </summary>
        internal static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New password  的本地化字符串。
        /// </summary>
        internal static string PasswordNew {
            get {
                return ResourceManager.GetString("PasswordNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste 的本地化字符串。
        /// </summary>
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Percent 的本地化字符串。
        /// </summary>
        internal static string PercentValue {
            get {
                return ResourceManager.GetString("PercentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permission 的本地化字符串。
        /// </summary>
        internal static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permission list 的本地化字符串。
        /// </summary>
        internal static string PermissionList {
            get {
                return ResourceManager.GetString("PermissionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Precision 的本地化字符串。
        /// </summary>
        internal static string Precision {
            get {
                return ResourceManager.GetString("Precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PropertyCopy 的本地化字符串。
        /// </summary>
        internal static string PropertyCopy {
            get {
                return ResourceManager.GetString("PropertyCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PropertyPaste 的本地化字符串。
        /// </summary>
        internal static string PropertyPaste {
            get {
                return ResourceManager.GetString("PropertyPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read 的本地化字符串。
        /// </summary>
        internal static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReadWrite 的本地化字符串。
        /// </summary>
        internal static string ReadWrite {
            get {
                return ResourceManager.GetString("ReadWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReadWriteMode 的本地化字符串。
        /// </summary>
        internal static string ReadWriteMode {
            get {
                return ResourceManager.GetString("ReadWriteMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Record 的本地化字符串。
        /// </summary>
        internal static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RecordType 的本地化字符串。
        /// </summary>
        internal static string RecordType {
            get {
                return ResourceManager.GetString("RecordType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registor 的本地化字符串。
        /// </summary>
        internal static string Registor {
            get {
                return ResourceManager.GetString("Registor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to remove {0}? 的本地化字符串。
        /// </summary>
        internal static string RemoveConfirmMsg {
            get {
                return ResourceManager.GetString("RemoveConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rename 的本地化字符串。
        /// </summary>
        internal static string ReName {
            get {
                return ResourceManager.GetString("ReName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace 的本地化字符串。
        /// </summary>
        internal static string Replace {
            get {
                return ResourceManager.GetString("Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace all 的本地化字符串。
        /// </summary>
        internal static string ReplaceAll {
            get {
                return ResourceManager.GetString("ReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReRun 的本地化字符串。
        /// </summary>
        internal static string ReRun {
            get {
                return ResourceManager.GetString("ReRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 save failed! 的本地化字符串。
        /// </summary>
        internal static string Savefailed {
            get {
                return ResourceManager.GetString("Savefailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data is changed,do you want to save? 的本地化字符串。
        /// </summary>
        internal static string saveprompt {
            get {
                return ResourceManager.GetString("saveprompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 save sucessfull! 的本地化字符串。
        /// </summary>
        internal static string SaveSucessful {
            get {
                return ResourceManager.GetString("SaveSucessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Security 的本地化字符串。
        /// </summary>
        internal static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a database 的本地化字符串。
        /// </summary>
        internal static string SelectDatabase {
            get {
                return ResourceManager.GetString("SelectDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected group 的本地化字符串。
        /// </summary>
        internal static string SelectGroup {
            get {
                return ResourceManager.GetString("SelectGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 History backup path 的本地化字符串。
        /// </summary>
        internal static string ServerBackupDataPath {
            get {
                return ResourceManager.GetString("ServerBackupDataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server Ip 的本地化字符串。
        /// </summary>
        internal static string ServerIp {
            get {
                return ResourceManager.GetString("ServerIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ServerPort 的本地化字符串。
        /// </summary>
        internal static string ServerPort {
            get {
                return ResourceManager.GetString("ServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 History data path 的本地化字符串。
        /// </summary>
        internal static string ServerPrimaryDataPath {
            get {
                return ResourceManager.GetString("ServerPrimaryDataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ServerSecurity 的本地化字符串。
        /// </summary>
        internal static string ServerSecurity {
            get {
                return ResourceManager.GetString("ServerSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server setting 的本地化字符串。
        /// </summary>
        internal static string ServerSetting {
            get {
                return ResourceManager.GetString("ServerSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SetDescription 的本地化字符串。
        /// </summary>
        internal static string SetDescription {
            get {
                return ResourceManager.GetString("SetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 set password fail. 的本地化字符串。
        /// </summary>
        internal static string SetPasswordfail {
            get {
                return ResourceManager.GetString("SetPasswordfail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 set password seccussfull. 的本地化字符串。
        /// </summary>
        internal static string SetPasswordSeccussful {
            get {
                return ResourceManager.GetString("SetPasswordSeccussful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slope zone 的本地化字符串。
        /// </summary>
        internal static string SlopeAreaValue {
            get {
                return ResourceManager.GetString("SlopeAreaValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slope 的本地化字符串。
        /// </summary>
        internal static string SlopeCompress {
            get {
                return ResourceManager.GetString("SlopeCompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run database 的本地化字符串。
        /// </summary>
        internal static string Start_Tooltip {
            get {
                return ResourceManager.GetString("Start_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start port 的本地化字符串。
        /// </summary>
        internal static string StartPort {
            get {
                return ResourceManager.GetString("StartPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop databse 的本地化字符串。
        /// </summary>
        internal static string Stop_Tooltip {
            get {
                return ResourceManager.GetString("Stop_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch 的本地化字符串。
        /// </summary>
        internal static string Switch {
            get {
                return ResourceManager.GetString("Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tag 的本地化字符串。
        /// </summary>
        internal static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tag count 的本地化字符串。
        /// </summary>
        internal static string TagCount {
            get {
                return ResourceManager.GetString("TagCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tag export complete! 的本地化字符串。
        /// </summary>
        internal static string TagExportComplete {
            get {
                return ResourceManager.GetString("TagExportComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query filter 的本地化字符串。
        /// </summary>
        internal static string TagFilter {
            get {
                return ResourceManager.GetString("TagFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tag group 的本地化字符串。
        /// </summary>
        internal static string TagGroup {
            get {
                return ResourceManager.GetString("TagGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timer 的本地化字符串。
        /// </summary>
        internal static string Timer {
            get {
                return ResourceManager.GetString("Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update tag {0} failed! 的本地化字符串。
        /// </summary>
        internal static string UpdateTagFail {
            get {
                return ResourceManager.GetString("UpdateTagFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User 的本地化字符串。
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User list 的本地化字符串。
        /// </summary>
        internal static string UserList {
            get {
                return ResourceManager.GetString("UserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User name 的本地化字符串。
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UseTls 的本地化字符串。
        /// </summary>
        internal static string UseTls {
            get {
                return ResourceManager.GetString("UseTls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ValueChanged 的本地化字符串。
        /// </summary>
        internal static string ValueChanged {
            get {
                return ResourceManager.GetString("ValueChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write 的本地化字符串。
        /// </summary>
        internal static string Write {
            get {
                return ResourceManager.GetString("Write", resourceCulture);
            }
        }
    }
}
