// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/developService.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DBDevelopService {

  /// <summary>Holder for reflection information generated from Protos/developService.proto</summary>
  public static partial class DevelopServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/developService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DevelopServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtQcm90b3MvZGV2ZWxvcFNlcnZpY2UucHJvdG8SEGRiRGV2ZWxvcFNlcnZp",
            "Y2UiRAoMTG9naW5SZXF1ZXN0EhAKCHVzZXJOYW1lGAEgASgJEhAKCHBhc3N3",
            "b3JkGAIgASgJEhAKCGRhdGFiYXNlGAMgASgJIh0KCkxvZ2luUmVwbHkSDwoH",
            "bG9naW5JZBgBIAEoCSKLAQoUQWRkVGFnUmVxdWVzdE1lc3NhZ2USDwoHbG9n",
            "aW5JZBgBIAEoCRIxCgdyZWFsVGFnGAIgASgLMiAuZGJEZXZlbG9wU2Vydmlj",
            "ZS5SZWFsVGFnTWVzc2FnZRIvCgZoaXNUYWcYAyABKAsyHy5kYkRldmVsb3BT",
            "ZXJ2aWNlLkhpc1RhZ01lc3NhZ2UiXQobVXBkYXRlUmVhbFRhZ1JlcXVlc3RN",
            "ZXNzYWdlEg8KB2xvZ2luSWQYASABKAkSLQoDdGFnGAIgASgLMiAuZGJEZXZl",
            "bG9wU2VydmljZS5SZWFsVGFnTWVzc2FnZSJbChpVcGRhdGVIaXNUYWdSZXF1",
            "ZXN0TWVzc2FnZRIPCgdsb2dpbklkGAEgASgJEiwKA3RhZxgCIAEoCzIfLmRi",
            "RGV2ZWxvcFNlcnZpY2UuSGlzVGFnTWVzc2FnZSIjChJBZGRUYWdSZXBseU1l",
            "c3NhZ2USDQoFVGFnSWQYASABKAUiMgoQUmVtb3ZlVGFnTWVzc2FnZRIPCgdM",
            "b2dpbklkGAEgASgJEg0KBVRhZ0lkGAIgAygFIlYKDFF1ZXJ5TWVzc2FnZRIP",
            "CgdMb2dpbklkGAEgASgJEjUKCmNvbmRpdGlvbnMYAiADKAsyIS5kYkRldmVs",
            "b3BTZXJ2aWNlLktleVZhbHVlTWVzc2FnZSItCg9LZXlWYWx1ZU1lc3NhZ2US",
            "CwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJIh0KCkdldFJlcXVlc3QSDwoH",
            "TG9naW5JZBgBIAEoCSIiChBCb29sUmVzdWx0UmVwbGF5Eg4KBlJlc3VsdBgB",
            "IAEoCCJMChZHZXRSZWFsVGFnTWVzc2FnZVJlcGx5EjIKCG1lc3NhZ2VzGAEg",
            "AygLMiAuZGJEZXZlbG9wU2VydmljZS5SZWFsVGFnTWVzc2FnZSJLChZHZXRI",
            "aXN0VGFnTWVzc2FnZVJlcGx5EjEKCG1lc3NhZ2VzGAEgAygLMh8uZGJEZXZl",
            "bG9wU2VydmljZS5IaXNUYWdNZXNzYWdlIm0KDlJlYWxUYWdNZXNzYWdlEgoK",
            "AklkGAEgASgNEg8KB1RhZ1R5cGUYAiABKA0SDAoETmFtZRgDIAEoCRINCgVH",
            "cm91cBgEIAEoCRIMCgREZXNjGAUgASgJEhMKC0xpbmtBZGRyZXNzGAYgASgJ",
            "IqQBCg1IaXNUYWdNZXNzYWdlEgoKAklkGAEgASgNEgwKBFR5cGUYAiABKA0S",
            "DwoHVGFnVHlwZRgDIAEoDRIUCgxDb21wcmVzc1R5cGUYBCABKA0SGgoSQ29t",
            "cHJlc3NQYXJhbWV0ZXIxGAUgASgCEhoKEkNvbXByZXNzUGFyYW1ldGVyMhgG",
            "IAEoAhIaChJDb21wcmVzc1BhcmFtZXRlcjMYByABKAIywwcKDURldmVsb3BT",
            "ZXJ2ZXISRQoFTG9naW4SHi5kYkRldmVsb3BTZXJ2aWNlLkxvZ2luUmVxdWVz",
            "dBocLmRiRGV2ZWxvcFNlcnZpY2UuTG9naW5SZXBseRJWCgZBZGRUYWcSJi5k",
            "YkRldmVsb3BTZXJ2aWNlLkFkZFRhZ1JlcXVlc3RNZXNzYWdlGiQuZGJEZXZl",
            "bG9wU2VydmljZS5BZGRUYWdSZXBseU1lc3NhZ2USUwoJUmVtb3ZlVGFnEiIu",
            "ZGJEZXZlbG9wU2VydmljZS5SZW1vdmVUYWdNZXNzYWdlGiIuZGJEZXZlbG9w",
            "U2VydmljZS5Cb29sUmVzdWx0UmVwbGF5ElcKDUdldFJlYWxBbGxUYWcSHC5k",
            "YkRldmVsb3BTZXJ2aWNlLkdldFJlcXVlc3QaKC5kYkRldmVsb3BTZXJ2aWNl",
            "LkdldFJlYWxUYWdNZXNzYWdlUmVwbHkSVgoMR2V0SGlzQWxsVGFnEhwuZGJE",
            "ZXZlbG9wU2VydmljZS5HZXRSZXF1ZXN0GiguZGJEZXZlbG9wU2VydmljZS5H",
            "ZXRIaXN0VGFnTWVzc2FnZVJlcGx5ElgKDFF1ZXJ5UmVhbFRhZxIeLmRiRGV2",
            "ZWxvcFNlcnZpY2UuUXVlcnlNZXNzYWdlGiguZGJEZXZlbG9wU2VydmljZS5H",
            "ZXRSZWFsVGFnTWVzc2FnZVJlcGx5ElcKC1F1ZXJ5SGlzVGFnEh4uZGJEZXZl",
            "bG9wU2VydmljZS5RdWVyeU1lc3NhZ2UaKC5kYkRldmVsb3BTZXJ2aWNlLkdl",
            "dEhpc3RUYWdNZXNzYWdlUmVwbHkSYgoNVXBkYXRlUmVhbFRhZxItLmRiRGV2",
            "ZWxvcFNlcnZpY2UuVXBkYXRlUmVhbFRhZ1JlcXVlc3RNZXNzYWdlGiIuZGJE",
            "ZXZlbG9wU2VydmljZS5Cb29sUmVzdWx0UmVwbGF5EmAKDFVwZGF0ZUhpc1Rh",
            "ZxIsLmRiRGV2ZWxvcFNlcnZpY2UuVXBkYXRlSGlzVGFnUmVxdWVzdE1lc3Nh",
            "Z2UaIi5kYkRldmVsb3BTZXJ2aWNlLkJvb2xSZXN1bHRSZXBsYXkSSAoEU2F2",
            "ZRIcLmRiRGV2ZWxvcFNlcnZpY2UuR2V0UmVxdWVzdBoiLmRiRGV2ZWxvcFNl",
            "cnZpY2UuQm9vbFJlc3VsdFJlcGxheRJKCgZDYW5jZWwSHC5kYkRldmVsb3BT",
            "ZXJ2aWNlLkdldFJlcXVlc3QaIi5kYkRldmVsb3BTZXJ2aWNlLkJvb2xSZXN1",
            "bHRSZXBsYXlCE6oCEERCRGV2ZWxvcFNlcnZpY2ViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DBDevelopService.LoginRequest), global::DBDevelopService.LoginRequest.Parser, new[]{ "UserName", "Password", "Database" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DBDevelopService.LoginReply), global::DBDevelopService.LoginReply.Parser, new[]{ "LoginId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DBDevelopService.AddTagRequestMessage), global::DBDevelopService.AddTagRequestMessage.Parser, new[]{ "LoginId", "RealTag", "HisTag" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DBDevelopService.UpdateRealTagRequestMessage), global::DBDevelopService.UpdateRealTagRequestMessage.Parser, new[]{ "LoginId", "Tag" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DBDevelopService.UpdateHisTagRequestMessage), global::DBDevelopService.UpdateHisTagRequestMessage.Parser, new[]{ "LoginId", "Tag" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DBDevelopService.AddTagReplyMessage), global::DBDevelopService.AddTagReplyMessage.Parser, new[]{ "TagId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DBDevelopService.RemoveTagMessage), global::DBDevelopService.RemoveTagMessage.Parser, new[]{ "LoginId", "TagId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DBDevelopService.QueryMessage), global::DBDevelopService.QueryMessage.Parser, new[]{ "LoginId", "Conditions" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DBDevelopService.KeyValueMessage), global::DBDevelopService.KeyValueMessage.Parser, new[]{ "Key", "Value" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DBDevelopService.GetRequest), global::DBDevelopService.GetRequest.Parser, new[]{ "LoginId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DBDevelopService.BoolResultReplay), global::DBDevelopService.BoolResultReplay.Parser, new[]{ "Result" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DBDevelopService.GetRealTagMessageReply), global::DBDevelopService.GetRealTagMessageReply.Parser, new[]{ "Messages" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DBDevelopService.GetHistTagMessageReply), global::DBDevelopService.GetHistTagMessageReply.Parser, new[]{ "Messages" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DBDevelopService.RealTagMessage), global::DBDevelopService.RealTagMessage.Parser, new[]{ "Id", "TagType", "Name", "Group", "Desc", "LinkAddress" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DBDevelopService.HisTagMessage), global::DBDevelopService.HisTagMessage.Parser, new[]{ "Id", "Type", "TagType", "CompressType", "CompressParameter1", "CompressParameter2", "CompressParameter3" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class LoginRequest : pb::IMessage<LoginRequest> {
    private static readonly pb::MessageParser<LoginRequest> _parser = new pb::MessageParser<LoginRequest>(() => new LoginRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LoginRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DBDevelopService.DevelopServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LoginRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LoginRequest(LoginRequest other) : this() {
      userName_ = other.userName_;
      password_ = other.password_;
      database_ = other.database_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LoginRequest Clone() {
      return new LoginRequest(this);
    }

    /// <summary>Field number for the "userName" field.</summary>
    public const int UserNameFieldNumber = 1;
    private string userName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UserName {
      get { return userName_; }
      set {
        userName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 2;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "database" field.</summary>
    public const int DatabaseFieldNumber = 3;
    private string database_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Database {
      get { return database_; }
      set {
        database_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LoginRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LoginRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UserName != other.UserName) return false;
      if (Password != other.Password) return false;
      if (Database != other.Database) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UserName.Length != 0) hash ^= UserName.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (Database.Length != 0) hash ^= Database.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UserName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UserName);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (Database.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Database);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UserName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserName);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (Database.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Database);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LoginRequest other) {
      if (other == null) {
        return;
      }
      if (other.UserName.Length != 0) {
        UserName = other.UserName;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      if (other.Database.Length != 0) {
        Database = other.Database;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            UserName = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
          case 26: {
            Database = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class LoginReply : pb::IMessage<LoginReply> {
    private static readonly pb::MessageParser<LoginReply> _parser = new pb::MessageParser<LoginReply>(() => new LoginReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LoginReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DBDevelopService.DevelopServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LoginReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LoginReply(LoginReply other) : this() {
      loginId_ = other.loginId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LoginReply Clone() {
      return new LoginReply(this);
    }

    /// <summary>Field number for the "loginId" field.</summary>
    public const int LoginIdFieldNumber = 1;
    private string loginId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LoginId {
      get { return loginId_; }
      set {
        loginId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LoginReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LoginReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LoginId != other.LoginId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (LoginId.Length != 0) hash ^= LoginId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (LoginId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(LoginId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (LoginId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LoginId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LoginReply other) {
      if (other == null) {
        return;
      }
      if (other.LoginId.Length != 0) {
        LoginId = other.LoginId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            LoginId = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// </summary>
  public sealed partial class AddTagRequestMessage : pb::IMessage<AddTagRequestMessage> {
    private static readonly pb::MessageParser<AddTagRequestMessage> _parser = new pb::MessageParser<AddTagRequestMessage>(() => new AddTagRequestMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AddTagRequestMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DBDevelopService.DevelopServiceReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddTagRequestMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddTagRequestMessage(AddTagRequestMessage other) : this() {
      loginId_ = other.loginId_;
      realTag_ = other.realTag_ != null ? other.realTag_.Clone() : null;
      hisTag_ = other.hisTag_ != null ? other.hisTag_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddTagRequestMessage Clone() {
      return new AddTagRequestMessage(this);
    }

    /// <summary>Field number for the "loginId" field.</summary>
    public const int LoginIdFieldNumber = 1;
    private string loginId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LoginId {
      get { return loginId_; }
      set {
        loginId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "realTag" field.</summary>
    public const int RealTagFieldNumber = 2;
    private global::DBDevelopService.RealTagMessage realTag_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DBDevelopService.RealTagMessage RealTag {
      get { return realTag_; }
      set {
        realTag_ = value;
      }
    }

    /// <summary>Field number for the "hisTag" field.</summary>
    public const int HisTagFieldNumber = 3;
    private global::DBDevelopService.HisTagMessage hisTag_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DBDevelopService.HisTagMessage HisTag {
      get { return hisTag_; }
      set {
        hisTag_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AddTagRequestMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AddTagRequestMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LoginId != other.LoginId) return false;
      if (!object.Equals(RealTag, other.RealTag)) return false;
      if (!object.Equals(HisTag, other.HisTag)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (LoginId.Length != 0) hash ^= LoginId.GetHashCode();
      if (realTag_ != null) hash ^= RealTag.GetHashCode();
      if (hisTag_ != null) hash ^= HisTag.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (LoginId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(LoginId);
      }
      if (realTag_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(RealTag);
      }
      if (hisTag_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(HisTag);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (LoginId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LoginId);
      }
      if (realTag_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RealTag);
      }
      if (hisTag_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(HisTag);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AddTagRequestMessage other) {
      if (other == null) {
        return;
      }
      if (other.LoginId.Length != 0) {
        LoginId = other.LoginId;
      }
      if (other.realTag_ != null) {
        if (realTag_ == null) {
          RealTag = new global::DBDevelopService.RealTagMessage();
        }
        RealTag.MergeFrom(other.RealTag);
      }
      if (other.hisTag_ != null) {
        if (hisTag_ == null) {
          HisTag = new global::DBDevelopService.HisTagMessage();
        }
        HisTag.MergeFrom(other.HisTag);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            LoginId = input.ReadString();
            break;
          }
          case 18: {
            if (realTag_ == null) {
              RealTag = new global::DBDevelopService.RealTagMessage();
            }
            input.ReadMessage(RealTag);
            break;
          }
          case 26: {
            if (hisTag_ == null) {
              HisTag = new global::DBDevelopService.HisTagMessage();
            }
            input.ReadMessage(HisTag);
            break;
          }
        }
      }
    }

  }

  public sealed partial class UpdateRealTagRequestMessage : pb::IMessage<UpdateRealTagRequestMessage> {
    private static readonly pb::MessageParser<UpdateRealTagRequestMessage> _parser = new pb::MessageParser<UpdateRealTagRequestMessage>(() => new UpdateRealTagRequestMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UpdateRealTagRequestMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DBDevelopService.DevelopServiceReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateRealTagRequestMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateRealTagRequestMessage(UpdateRealTagRequestMessage other) : this() {
      loginId_ = other.loginId_;
      tag_ = other.tag_ != null ? other.tag_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateRealTagRequestMessage Clone() {
      return new UpdateRealTagRequestMessage(this);
    }

    /// <summary>Field number for the "loginId" field.</summary>
    public const int LoginIdFieldNumber = 1;
    private string loginId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LoginId {
      get { return loginId_; }
      set {
        loginId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "tag" field.</summary>
    public const int TagFieldNumber = 2;
    private global::DBDevelopService.RealTagMessage tag_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DBDevelopService.RealTagMessage Tag {
      get { return tag_; }
      set {
        tag_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UpdateRealTagRequestMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UpdateRealTagRequestMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LoginId != other.LoginId) return false;
      if (!object.Equals(Tag, other.Tag)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (LoginId.Length != 0) hash ^= LoginId.GetHashCode();
      if (tag_ != null) hash ^= Tag.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (LoginId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(LoginId);
      }
      if (tag_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Tag);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (LoginId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LoginId);
      }
      if (tag_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Tag);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UpdateRealTagRequestMessage other) {
      if (other == null) {
        return;
      }
      if (other.LoginId.Length != 0) {
        LoginId = other.LoginId;
      }
      if (other.tag_ != null) {
        if (tag_ == null) {
          Tag = new global::DBDevelopService.RealTagMessage();
        }
        Tag.MergeFrom(other.Tag);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            LoginId = input.ReadString();
            break;
          }
          case 18: {
            if (tag_ == null) {
              Tag = new global::DBDevelopService.RealTagMessage();
            }
            input.ReadMessage(Tag);
            break;
          }
        }
      }
    }

  }

  public sealed partial class UpdateHisTagRequestMessage : pb::IMessage<UpdateHisTagRequestMessage> {
    private static readonly pb::MessageParser<UpdateHisTagRequestMessage> _parser = new pb::MessageParser<UpdateHisTagRequestMessage>(() => new UpdateHisTagRequestMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UpdateHisTagRequestMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DBDevelopService.DevelopServiceReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateHisTagRequestMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateHisTagRequestMessage(UpdateHisTagRequestMessage other) : this() {
      loginId_ = other.loginId_;
      tag_ = other.tag_ != null ? other.tag_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateHisTagRequestMessage Clone() {
      return new UpdateHisTagRequestMessage(this);
    }

    /// <summary>Field number for the "loginId" field.</summary>
    public const int LoginIdFieldNumber = 1;
    private string loginId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LoginId {
      get { return loginId_; }
      set {
        loginId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "tag" field.</summary>
    public const int TagFieldNumber = 2;
    private global::DBDevelopService.HisTagMessage tag_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DBDevelopService.HisTagMessage Tag {
      get { return tag_; }
      set {
        tag_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UpdateHisTagRequestMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UpdateHisTagRequestMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LoginId != other.LoginId) return false;
      if (!object.Equals(Tag, other.Tag)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (LoginId.Length != 0) hash ^= LoginId.GetHashCode();
      if (tag_ != null) hash ^= Tag.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (LoginId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(LoginId);
      }
      if (tag_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Tag);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (LoginId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LoginId);
      }
      if (tag_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Tag);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UpdateHisTagRequestMessage other) {
      if (other == null) {
        return;
      }
      if (other.LoginId.Length != 0) {
        LoginId = other.LoginId;
      }
      if (other.tag_ != null) {
        if (tag_ == null) {
          Tag = new global::DBDevelopService.HisTagMessage();
        }
        Tag.MergeFrom(other.Tag);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            LoginId = input.ReadString();
            break;
          }
          case 18: {
            if (tag_ == null) {
              Tag = new global::DBDevelopService.HisTagMessage();
            }
            input.ReadMessage(Tag);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// </summary>
  public sealed partial class AddTagReplyMessage : pb::IMessage<AddTagReplyMessage> {
    private static readonly pb::MessageParser<AddTagReplyMessage> _parser = new pb::MessageParser<AddTagReplyMessage>(() => new AddTagReplyMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AddTagReplyMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DBDevelopService.DevelopServiceReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddTagReplyMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddTagReplyMessage(AddTagReplyMessage other) : this() {
      tagId_ = other.tagId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddTagReplyMessage Clone() {
      return new AddTagReplyMessage(this);
    }

    /// <summary>Field number for the "TagId" field.</summary>
    public const int TagIdFieldNumber = 1;
    private int tagId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TagId {
      get { return tagId_; }
      set {
        tagId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AddTagReplyMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AddTagReplyMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TagId != other.TagId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (TagId != 0) hash ^= TagId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (TagId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TagId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (TagId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TagId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AddTagReplyMessage other) {
      if (other == null) {
        return;
      }
      if (other.TagId != 0) {
        TagId = other.TagId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TagId = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class RemoveTagMessage : pb::IMessage<RemoveTagMessage> {
    private static readonly pb::MessageParser<RemoveTagMessage> _parser = new pb::MessageParser<RemoveTagMessage>(() => new RemoveTagMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RemoveTagMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DBDevelopService.DevelopServiceReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RemoveTagMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RemoveTagMessage(RemoveTagMessage other) : this() {
      loginId_ = other.loginId_;
      tagId_ = other.tagId_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RemoveTagMessage Clone() {
      return new RemoveTagMessage(this);
    }

    /// <summary>Field number for the "LoginId" field.</summary>
    public const int LoginIdFieldNumber = 1;
    private string loginId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LoginId {
      get { return loginId_; }
      set {
        loginId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "TagId" field.</summary>
    public const int TagIdFieldNumber = 2;
    private static readonly pb::FieldCodec<int> _repeated_tagId_codec
        = pb::FieldCodec.ForInt32(18);
    private readonly pbc::RepeatedField<int> tagId_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> TagId {
      get { return tagId_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RemoveTagMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RemoveTagMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LoginId != other.LoginId) return false;
      if(!tagId_.Equals(other.tagId_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (LoginId.Length != 0) hash ^= LoginId.GetHashCode();
      hash ^= tagId_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (LoginId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(LoginId);
      }
      tagId_.WriteTo(output, _repeated_tagId_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (LoginId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LoginId);
      }
      size += tagId_.CalculateSize(_repeated_tagId_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RemoveTagMessage other) {
      if (other == null) {
        return;
      }
      if (other.LoginId.Length != 0) {
        LoginId = other.LoginId;
      }
      tagId_.Add(other.tagId_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            LoginId = input.ReadString();
            break;
          }
          case 18:
          case 16: {
            tagId_.AddEntriesFrom(input, _repeated_tagId_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// </summary>
  public sealed partial class QueryMessage : pb::IMessage<QueryMessage> {
    private static readonly pb::MessageParser<QueryMessage> _parser = new pb::MessageParser<QueryMessage>(() => new QueryMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<QueryMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DBDevelopService.DevelopServiceReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QueryMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QueryMessage(QueryMessage other) : this() {
      loginId_ = other.loginId_;
      conditions_ = other.conditions_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QueryMessage Clone() {
      return new QueryMessage(this);
    }

    /// <summary>Field number for the "LoginId" field.</summary>
    public const int LoginIdFieldNumber = 1;
    private string loginId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LoginId {
      get { return loginId_; }
      set {
        loginId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "conditions" field.</summary>
    public const int ConditionsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::DBDevelopService.KeyValueMessage> _repeated_conditions_codec
        = pb::FieldCodec.ForMessage(18, global::DBDevelopService.KeyValueMessage.Parser);
    private readonly pbc::RepeatedField<global::DBDevelopService.KeyValueMessage> conditions_ = new pbc::RepeatedField<global::DBDevelopService.KeyValueMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::DBDevelopService.KeyValueMessage> Conditions {
      get { return conditions_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as QueryMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(QueryMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LoginId != other.LoginId) return false;
      if(!conditions_.Equals(other.conditions_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (LoginId.Length != 0) hash ^= LoginId.GetHashCode();
      hash ^= conditions_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (LoginId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(LoginId);
      }
      conditions_.WriteTo(output, _repeated_conditions_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (LoginId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LoginId);
      }
      size += conditions_.CalculateSize(_repeated_conditions_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(QueryMessage other) {
      if (other == null) {
        return;
      }
      if (other.LoginId.Length != 0) {
        LoginId = other.LoginId;
      }
      conditions_.Add(other.conditions_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            LoginId = input.ReadString();
            break;
          }
          case 18: {
            conditions_.AddEntriesFrom(input, _repeated_conditions_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// </summary>
  public sealed partial class KeyValueMessage : pb::IMessage<KeyValueMessage> {
    private static readonly pb::MessageParser<KeyValueMessage> _parser = new pb::MessageParser<KeyValueMessage>(() => new KeyValueMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<KeyValueMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DBDevelopService.DevelopServiceReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public KeyValueMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public KeyValueMessage(KeyValueMessage other) : this() {
      key_ = other.key_;
      value_ = other.value_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public KeyValueMessage Clone() {
      return new KeyValueMessage(this);
    }

    /// <summary>Field number for the "key" field.</summary>
    public const int KeyFieldNumber = 1;
    private string key_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Key {
      get { return key_; }
      set {
        key_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 2;
    private string value_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Value {
      get { return value_; }
      set {
        value_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as KeyValueMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(KeyValueMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Key != other.Key) return false;
      if (Value != other.Value) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Key.Length != 0) hash ^= Key.GetHashCode();
      if (Value.Length != 0) hash ^= Value.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Key.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Key);
      }
      if (Value.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Value);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Key.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Key);
      }
      if (Value.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Value);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(KeyValueMessage other) {
      if (other == null) {
        return;
      }
      if (other.Key.Length != 0) {
        Key = other.Key;
      }
      if (other.Value.Length != 0) {
        Value = other.Value;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Key = input.ReadString();
            break;
          }
          case 18: {
            Value = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// </summary>
  public sealed partial class GetRequest : pb::IMessage<GetRequest> {
    private static readonly pb::MessageParser<GetRequest> _parser = new pb::MessageParser<GetRequest>(() => new GetRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DBDevelopService.DevelopServiceReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetRequest(GetRequest other) : this() {
      loginId_ = other.loginId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetRequest Clone() {
      return new GetRequest(this);
    }

    /// <summary>Field number for the "LoginId" field.</summary>
    public const int LoginIdFieldNumber = 1;
    private string loginId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LoginId {
      get { return loginId_; }
      set {
        loginId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LoginId != other.LoginId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (LoginId.Length != 0) hash ^= LoginId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (LoginId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(LoginId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (LoginId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LoginId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetRequest other) {
      if (other == null) {
        return;
      }
      if (other.LoginId.Length != 0) {
        LoginId = other.LoginId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            LoginId = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// </summary>
  public sealed partial class BoolResultReplay : pb::IMessage<BoolResultReplay> {
    private static readonly pb::MessageParser<BoolResultReplay> _parser = new pb::MessageParser<BoolResultReplay>(() => new BoolResultReplay());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BoolResultReplay> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DBDevelopService.DevelopServiceReflection.Descriptor.MessageTypes[10]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BoolResultReplay() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BoolResultReplay(BoolResultReplay other) : this() {
      result_ = other.result_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BoolResultReplay Clone() {
      return new BoolResultReplay(this);
    }

    /// <summary>Field number for the "Result" field.</summary>
    public const int ResultFieldNumber = 1;
    private bool result_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BoolResultReplay);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BoolResultReplay other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != false) hash ^= Result.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Result != false) {
        output.WriteRawTag(8);
        output.WriteBool(Result);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BoolResultReplay other) {
      if (other == null) {
        return;
      }
      if (other.Result != false) {
        Result = other.Result;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Result = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetRealTagMessageReply : pb::IMessage<GetRealTagMessageReply> {
    private static readonly pb::MessageParser<GetRealTagMessageReply> _parser = new pb::MessageParser<GetRealTagMessageReply>(() => new GetRealTagMessageReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetRealTagMessageReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DBDevelopService.DevelopServiceReflection.Descriptor.MessageTypes[11]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetRealTagMessageReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetRealTagMessageReply(GetRealTagMessageReply other) : this() {
      messages_ = other.messages_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetRealTagMessageReply Clone() {
      return new GetRealTagMessageReply(this);
    }

    /// <summary>Field number for the "messages" field.</summary>
    public const int MessagesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::DBDevelopService.RealTagMessage> _repeated_messages_codec
        = pb::FieldCodec.ForMessage(10, global::DBDevelopService.RealTagMessage.Parser);
    private readonly pbc::RepeatedField<global::DBDevelopService.RealTagMessage> messages_ = new pbc::RepeatedField<global::DBDevelopService.RealTagMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::DBDevelopService.RealTagMessage> Messages {
      get { return messages_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetRealTagMessageReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetRealTagMessageReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!messages_.Equals(other.messages_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= messages_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      messages_.WriteTo(output, _repeated_messages_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += messages_.CalculateSize(_repeated_messages_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetRealTagMessageReply other) {
      if (other == null) {
        return;
      }
      messages_.Add(other.messages_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            messages_.AddEntriesFrom(input, _repeated_messages_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetHistTagMessageReply : pb::IMessage<GetHistTagMessageReply> {
    private static readonly pb::MessageParser<GetHistTagMessageReply> _parser = new pb::MessageParser<GetHistTagMessageReply>(() => new GetHistTagMessageReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetHistTagMessageReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DBDevelopService.DevelopServiceReflection.Descriptor.MessageTypes[12]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetHistTagMessageReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetHistTagMessageReply(GetHistTagMessageReply other) : this() {
      messages_ = other.messages_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetHistTagMessageReply Clone() {
      return new GetHistTagMessageReply(this);
    }

    /// <summary>Field number for the "messages" field.</summary>
    public const int MessagesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::DBDevelopService.HisTagMessage> _repeated_messages_codec
        = pb::FieldCodec.ForMessage(10, global::DBDevelopService.HisTagMessage.Parser);
    private readonly pbc::RepeatedField<global::DBDevelopService.HisTagMessage> messages_ = new pbc::RepeatedField<global::DBDevelopService.HisTagMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::DBDevelopService.HisTagMessage> Messages {
      get { return messages_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetHistTagMessageReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetHistTagMessageReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!messages_.Equals(other.messages_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= messages_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      messages_.WriteTo(output, _repeated_messages_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += messages_.CalculateSize(_repeated_messages_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetHistTagMessageReply other) {
      if (other == null) {
        return;
      }
      messages_.Add(other.messages_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            messages_.AddEntriesFrom(input, _repeated_messages_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///实时变量配置
  /// </summary>
  public sealed partial class RealTagMessage : pb::IMessage<RealTagMessage> {
    private static readonly pb::MessageParser<RealTagMessage> _parser = new pb::MessageParser<RealTagMessage>(() => new RealTagMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RealTagMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DBDevelopService.DevelopServiceReflection.Descriptor.MessageTypes[13]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RealTagMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RealTagMessage(RealTagMessage other) : this() {
      id_ = other.id_;
      tagType_ = other.tagType_;
      name_ = other.name_;
      group_ = other.group_;
      desc_ = other.desc_;
      linkAddress_ = other.linkAddress_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RealTagMessage Clone() {
      return new RealTagMessage(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private uint id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "TagType" field.</summary>
    public const int TagTypeFieldNumber = 2;
    private uint tagType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint TagType {
      get { return tagType_; }
      set {
        tagType_ = value;
      }
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 3;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Group" field.</summary>
    public const int GroupFieldNumber = 4;
    private string group_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Group {
      get { return group_; }
      set {
        group_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Desc" field.</summary>
    public const int DescFieldNumber = 5;
    private string desc_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Desc {
      get { return desc_; }
      set {
        desc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "LinkAddress" field.</summary>
    public const int LinkAddressFieldNumber = 6;
    private string linkAddress_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LinkAddress {
      get { return linkAddress_; }
      set {
        linkAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RealTagMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RealTagMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (TagType != other.TagType) return false;
      if (Name != other.Name) return false;
      if (Group != other.Group) return false;
      if (Desc != other.Desc) return false;
      if (LinkAddress != other.LinkAddress) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (TagType != 0) hash ^= TagType.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Group.Length != 0) hash ^= Group.GetHashCode();
      if (Desc.Length != 0) hash ^= Desc.GetHashCode();
      if (LinkAddress.Length != 0) hash ^= LinkAddress.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Id);
      }
      if (TagType != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(TagType);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (Group.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Group);
      }
      if (Desc.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Desc);
      }
      if (LinkAddress.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(LinkAddress);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Id);
      }
      if (TagType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TagType);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Group.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Group);
      }
      if (Desc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Desc);
      }
      if (LinkAddress.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LinkAddress);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RealTagMessage other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.TagType != 0) {
        TagType = other.TagType;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Group.Length != 0) {
        Group = other.Group;
      }
      if (other.Desc.Length != 0) {
        Desc = other.Desc;
      }
      if (other.LinkAddress.Length != 0) {
        LinkAddress = other.LinkAddress;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadUInt32();
            break;
          }
          case 16: {
            TagType = input.ReadUInt32();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 34: {
            Group = input.ReadString();
            break;
          }
          case 42: {
            Desc = input.ReadString();
            break;
          }
          case 50: {
            LinkAddress = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///历史变量定义
  /// </summary>
  public sealed partial class HisTagMessage : pb::IMessage<HisTagMessage> {
    private static readonly pb::MessageParser<HisTagMessage> _parser = new pb::MessageParser<HisTagMessage>(() => new HisTagMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<HisTagMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DBDevelopService.DevelopServiceReflection.Descriptor.MessageTypes[14]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HisTagMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HisTagMessage(HisTagMessage other) : this() {
      id_ = other.id_;
      type_ = other.type_;
      tagType_ = other.tagType_;
      compressType_ = other.compressType_;
      compressParameter1_ = other.compressParameter1_;
      compressParameter2_ = other.compressParameter2_;
      compressParameter3_ = other.compressParameter3_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HisTagMessage Clone() {
      return new HisTagMessage(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private uint id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "Type" field.</summary>
    public const int TypeFieldNumber = 2;
    private uint type_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "TagType" field.</summary>
    public const int TagTypeFieldNumber = 3;
    private uint tagType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint TagType {
      get { return tagType_; }
      set {
        tagType_ = value;
      }
    }

    /// <summary>Field number for the "CompressType" field.</summary>
    public const int CompressTypeFieldNumber = 4;
    private uint compressType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint CompressType {
      get { return compressType_; }
      set {
        compressType_ = value;
      }
    }

    /// <summary>Field number for the "CompressParameter1" field.</summary>
    public const int CompressParameter1FieldNumber = 5;
    private float compressParameter1_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float CompressParameter1 {
      get { return compressParameter1_; }
      set {
        compressParameter1_ = value;
      }
    }

    /// <summary>Field number for the "CompressParameter2" field.</summary>
    public const int CompressParameter2FieldNumber = 6;
    private float compressParameter2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float CompressParameter2 {
      get { return compressParameter2_; }
      set {
        compressParameter2_ = value;
      }
    }

    /// <summary>Field number for the "CompressParameter3" field.</summary>
    public const int CompressParameter3FieldNumber = 7;
    private float compressParameter3_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float CompressParameter3 {
      get { return compressParameter3_; }
      set {
        compressParameter3_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as HisTagMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(HisTagMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Type != other.Type) return false;
      if (TagType != other.TagType) return false;
      if (CompressType != other.CompressType) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(CompressParameter1, other.CompressParameter1)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(CompressParameter2, other.CompressParameter2)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(CompressParameter3, other.CompressParameter3)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Type != 0) hash ^= Type.GetHashCode();
      if (TagType != 0) hash ^= TagType.GetHashCode();
      if (CompressType != 0) hash ^= CompressType.GetHashCode();
      if (CompressParameter1 != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(CompressParameter1);
      if (CompressParameter2 != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(CompressParameter2);
      if (CompressParameter3 != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(CompressParameter3);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Id);
      }
      if (Type != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Type);
      }
      if (TagType != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(TagType);
      }
      if (CompressType != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(CompressType);
      }
      if (CompressParameter1 != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(CompressParameter1);
      }
      if (CompressParameter2 != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(CompressParameter2);
      }
      if (CompressParameter3 != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(CompressParameter3);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Id);
      }
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Type);
      }
      if (TagType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TagType);
      }
      if (CompressType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CompressType);
      }
      if (CompressParameter1 != 0F) {
        size += 1 + 4;
      }
      if (CompressParameter2 != 0F) {
        size += 1 + 4;
      }
      if (CompressParameter3 != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(HisTagMessage other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.TagType != 0) {
        TagType = other.TagType;
      }
      if (other.CompressType != 0) {
        CompressType = other.CompressType;
      }
      if (other.CompressParameter1 != 0F) {
        CompressParameter1 = other.CompressParameter1;
      }
      if (other.CompressParameter2 != 0F) {
        CompressParameter2 = other.CompressParameter2;
      }
      if (other.CompressParameter3 != 0F) {
        CompressParameter3 = other.CompressParameter3;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadUInt32();
            break;
          }
          case 16: {
            Type = input.ReadUInt32();
            break;
          }
          case 24: {
            TagType = input.ReadUInt32();
            break;
          }
          case 32: {
            CompressType = input.ReadUInt32();
            break;
          }
          case 45: {
            CompressParameter1 = input.ReadFloat();
            break;
          }
          case 53: {
            CompressParameter2 = input.ReadFloat();
            break;
          }
          case 61: {
            CompressParameter3 = input.ReadFloat();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
