// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/developService.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace DBDevelopService {
  /// <summary>
  /// The greeting service definition.
  /// </summary>
  public static partial class DevelopServer
  {
    static readonly string __ServiceName = "dbDevelopService.DevelopServer";

    static readonly grpc::Marshaller<global::DBDevelopService.LoginRequest> __Marshaller_dbDevelopService_LoginRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DBDevelopService.LoginRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::DBDevelopService.LoginReply> __Marshaller_dbDevelopService_LoginReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DBDevelopService.LoginReply.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::DBDevelopService.AddTagRequestMessage> __Marshaller_dbDevelopService_AddTagRequestMessage = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DBDevelopService.AddTagRequestMessage.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::DBDevelopService.AddTagReplyMessage> __Marshaller_dbDevelopService_AddTagReplyMessage = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DBDevelopService.AddTagReplyMessage.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::DBDevelopService.RemoveTagMessage> __Marshaller_dbDevelopService_RemoveTagMessage = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DBDevelopService.RemoveTagMessage.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::DBDevelopService.BoolResultReplay> __Marshaller_dbDevelopService_BoolResultReplay = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DBDevelopService.BoolResultReplay.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::DBDevelopService.GetRequest> __Marshaller_dbDevelopService_GetRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DBDevelopService.GetRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::DBDevelopService.GetRealTagMessageReply> __Marshaller_dbDevelopService_GetRealTagMessageReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DBDevelopService.GetRealTagMessageReply.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::DBDevelopService.GetHistTagMessageReply> __Marshaller_dbDevelopService_GetHistTagMessageReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DBDevelopService.GetHistTagMessageReply.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::DBDevelopService.QueryMessage> __Marshaller_dbDevelopService_QueryMessage = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DBDevelopService.QueryMessage.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::DBDevelopService.UpdateRealTagRequestMessage> __Marshaller_dbDevelopService_UpdateRealTagRequestMessage = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DBDevelopService.UpdateRealTagRequestMessage.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::DBDevelopService.UpdateHisTagRequestMessage> __Marshaller_dbDevelopService_UpdateHisTagRequestMessage = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DBDevelopService.UpdateHisTagRequestMessage.Parser.ParseFrom);

    static readonly grpc::Method<global::DBDevelopService.LoginRequest, global::DBDevelopService.LoginReply> __Method_Login = new grpc::Method<global::DBDevelopService.LoginRequest, global::DBDevelopService.LoginReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Login",
        __Marshaller_dbDevelopService_LoginRequest,
        __Marshaller_dbDevelopService_LoginReply);

    static readonly grpc::Method<global::DBDevelopService.AddTagRequestMessage, global::DBDevelopService.AddTagReplyMessage> __Method_AddTag = new grpc::Method<global::DBDevelopService.AddTagRequestMessage, global::DBDevelopService.AddTagReplyMessage>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddTag",
        __Marshaller_dbDevelopService_AddTagRequestMessage,
        __Marshaller_dbDevelopService_AddTagReplyMessage);

    static readonly grpc::Method<global::DBDevelopService.RemoveTagMessage, global::DBDevelopService.BoolResultReplay> __Method_RemoveTag = new grpc::Method<global::DBDevelopService.RemoveTagMessage, global::DBDevelopService.BoolResultReplay>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RemoveTag",
        __Marshaller_dbDevelopService_RemoveTagMessage,
        __Marshaller_dbDevelopService_BoolResultReplay);

    static readonly grpc::Method<global::DBDevelopService.GetRequest, global::DBDevelopService.GetRealTagMessageReply> __Method_GetRealAllTag = new grpc::Method<global::DBDevelopService.GetRequest, global::DBDevelopService.GetRealTagMessageReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetRealAllTag",
        __Marshaller_dbDevelopService_GetRequest,
        __Marshaller_dbDevelopService_GetRealTagMessageReply);

    static readonly grpc::Method<global::DBDevelopService.GetRequest, global::DBDevelopService.GetHistTagMessageReply> __Method_GetHisAllTag = new grpc::Method<global::DBDevelopService.GetRequest, global::DBDevelopService.GetHistTagMessageReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetHisAllTag",
        __Marshaller_dbDevelopService_GetRequest,
        __Marshaller_dbDevelopService_GetHistTagMessageReply);

    static readonly grpc::Method<global::DBDevelopService.QueryMessage, global::DBDevelopService.GetRealTagMessageReply> __Method_QueryRealTag = new grpc::Method<global::DBDevelopService.QueryMessage, global::DBDevelopService.GetRealTagMessageReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "QueryRealTag",
        __Marshaller_dbDevelopService_QueryMessage,
        __Marshaller_dbDevelopService_GetRealTagMessageReply);

    static readonly grpc::Method<global::DBDevelopService.QueryMessage, global::DBDevelopService.GetHistTagMessageReply> __Method_QueryHisTag = new grpc::Method<global::DBDevelopService.QueryMessage, global::DBDevelopService.GetHistTagMessageReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "QueryHisTag",
        __Marshaller_dbDevelopService_QueryMessage,
        __Marshaller_dbDevelopService_GetHistTagMessageReply);

    static readonly grpc::Method<global::DBDevelopService.UpdateRealTagRequestMessage, global::DBDevelopService.BoolResultReplay> __Method_UpdateRealTag = new grpc::Method<global::DBDevelopService.UpdateRealTagRequestMessage, global::DBDevelopService.BoolResultReplay>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateRealTag",
        __Marshaller_dbDevelopService_UpdateRealTagRequestMessage,
        __Marshaller_dbDevelopService_BoolResultReplay);

    static readonly grpc::Method<global::DBDevelopService.UpdateHisTagRequestMessage, global::DBDevelopService.BoolResultReplay> __Method_UpdateHisTag = new grpc::Method<global::DBDevelopService.UpdateHisTagRequestMessage, global::DBDevelopService.BoolResultReplay>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateHisTag",
        __Marshaller_dbDevelopService_UpdateHisTagRequestMessage,
        __Marshaller_dbDevelopService_BoolResultReplay);

    static readonly grpc::Method<global::DBDevelopService.GetRequest, global::DBDevelopService.BoolResultReplay> __Method_Save = new grpc::Method<global::DBDevelopService.GetRequest, global::DBDevelopService.BoolResultReplay>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Save",
        __Marshaller_dbDevelopService_GetRequest,
        __Marshaller_dbDevelopService_BoolResultReplay);

    static readonly grpc::Method<global::DBDevelopService.GetRequest, global::DBDevelopService.BoolResultReplay> __Method_Cancel = new grpc::Method<global::DBDevelopService.GetRequest, global::DBDevelopService.BoolResultReplay>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Cancel",
        __Marshaller_dbDevelopService_GetRequest,
        __Marshaller_dbDevelopService_BoolResultReplay);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::DBDevelopService.DevelopServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for DevelopServer</summary>
    public partial class DevelopServerClient : grpc::ClientBase<DevelopServerClient>
    {
      /// <summary>Creates a new client for DevelopServer</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public DevelopServerClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for DevelopServer that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public DevelopServerClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected DevelopServerClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected DevelopServerClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      ///Login
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::DBDevelopService.LoginReply Login(global::DBDevelopService.LoginRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Login(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Login
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::DBDevelopService.LoginReply Login(global::DBDevelopService.LoginRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Login, null, options, request);
      }
      /// <summary>
      ///Login
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::DBDevelopService.LoginReply> LoginAsync(global::DBDevelopService.LoginRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return LoginAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Login
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::DBDevelopService.LoginReply> LoginAsync(global::DBDevelopService.LoginRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Login, null, options, request);
      }
      /// <summary>
      ///添加
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::DBDevelopService.AddTagReplyMessage AddTag(global::DBDevelopService.AddTagRequestMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddTag(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///添加
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::DBDevelopService.AddTagReplyMessage AddTag(global::DBDevelopService.AddTagRequestMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddTag, null, options, request);
      }
      /// <summary>
      ///添加
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::DBDevelopService.AddTagReplyMessage> AddTagAsync(global::DBDevelopService.AddTagRequestMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddTagAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///添加
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::DBDevelopService.AddTagReplyMessage> AddTagAsync(global::DBDevelopService.AddTagRequestMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddTag, null, options, request);
      }
      /// <summary>
      ///删除
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::DBDevelopService.BoolResultReplay RemoveTag(global::DBDevelopService.RemoveTagMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RemoveTag(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///删除
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::DBDevelopService.BoolResultReplay RemoveTag(global::DBDevelopService.RemoveTagMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RemoveTag, null, options, request);
      }
      /// <summary>
      ///删除
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::DBDevelopService.BoolResultReplay> RemoveTagAsync(global::DBDevelopService.RemoveTagMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RemoveTagAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///删除
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::DBDevelopService.BoolResultReplay> RemoveTagAsync(global::DBDevelopService.RemoveTagMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RemoveTag, null, options, request);
      }
      /// <summary>
      ///查询
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::DBDevelopService.GetRealTagMessageReply GetRealAllTag(global::DBDevelopService.GetRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRealAllTag(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///查询
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::DBDevelopService.GetRealTagMessageReply GetRealAllTag(global::DBDevelopService.GetRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetRealAllTag, null, options, request);
      }
      /// <summary>
      ///查询
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::DBDevelopService.GetRealTagMessageReply> GetRealAllTagAsync(global::DBDevelopService.GetRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRealAllTagAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///查询
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::DBDevelopService.GetRealTagMessageReply> GetRealAllTagAsync(global::DBDevelopService.GetRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetRealAllTag, null, options, request);
      }
      /// <summary>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::DBDevelopService.GetHistTagMessageReply GetHisAllTag(global::DBDevelopService.GetRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetHisAllTag(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::DBDevelopService.GetHistTagMessageReply GetHisAllTag(global::DBDevelopService.GetRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetHisAllTag, null, options, request);
      }
      /// <summary>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::DBDevelopService.GetHistTagMessageReply> GetHisAllTagAsync(global::DBDevelopService.GetRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetHisAllTagAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::DBDevelopService.GetHistTagMessageReply> GetHisAllTagAsync(global::DBDevelopService.GetRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetHisAllTag, null, options, request);
      }
      /// <summary>
      ///查询指定条件的变量
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::DBDevelopService.GetRealTagMessageReply QueryRealTag(global::DBDevelopService.QueryMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return QueryRealTag(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///查询指定条件的变量
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::DBDevelopService.GetRealTagMessageReply QueryRealTag(global::DBDevelopService.QueryMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_QueryRealTag, null, options, request);
      }
      /// <summary>
      ///查询指定条件的变量
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::DBDevelopService.GetRealTagMessageReply> QueryRealTagAsync(global::DBDevelopService.QueryMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return QueryRealTagAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///查询指定条件的变量
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::DBDevelopService.GetRealTagMessageReply> QueryRealTagAsync(global::DBDevelopService.QueryMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_QueryRealTag, null, options, request);
      }
      public virtual global::DBDevelopService.GetHistTagMessageReply QueryHisTag(global::DBDevelopService.QueryMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return QueryHisTag(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::DBDevelopService.GetHistTagMessageReply QueryHisTag(global::DBDevelopService.QueryMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_QueryHisTag, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::DBDevelopService.GetHistTagMessageReply> QueryHisTagAsync(global::DBDevelopService.QueryMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return QueryHisTagAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::DBDevelopService.GetHistTagMessageReply> QueryHisTagAsync(global::DBDevelopService.QueryMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_QueryHisTag, null, options, request);
      }
      /// <summary>
      ///修改实时变量
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::DBDevelopService.BoolResultReplay UpdateRealTag(global::DBDevelopService.UpdateRealTagRequestMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateRealTag(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///修改实时变量
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::DBDevelopService.BoolResultReplay UpdateRealTag(global::DBDevelopService.UpdateRealTagRequestMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateRealTag, null, options, request);
      }
      /// <summary>
      ///修改实时变量
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::DBDevelopService.BoolResultReplay> UpdateRealTagAsync(global::DBDevelopService.UpdateRealTagRequestMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateRealTagAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///修改实时变量
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::DBDevelopService.BoolResultReplay> UpdateRealTagAsync(global::DBDevelopService.UpdateRealTagRequestMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateRealTag, null, options, request);
      }
      /// <summary>
      ///修改历史变量
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::DBDevelopService.BoolResultReplay UpdateHisTag(global::DBDevelopService.UpdateHisTagRequestMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateHisTag(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///修改历史变量
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::DBDevelopService.BoolResultReplay UpdateHisTag(global::DBDevelopService.UpdateHisTagRequestMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateHisTag, null, options, request);
      }
      /// <summary>
      ///修改历史变量
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::DBDevelopService.BoolResultReplay> UpdateHisTagAsync(global::DBDevelopService.UpdateHisTagRequestMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateHisTagAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///修改历史变量
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::DBDevelopService.BoolResultReplay> UpdateHisTagAsync(global::DBDevelopService.UpdateHisTagRequestMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateHisTag, null, options, request);
      }
      /// <summary>
      ///保存
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::DBDevelopService.BoolResultReplay Save(global::DBDevelopService.GetRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Save(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///保存
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::DBDevelopService.BoolResultReplay Save(global::DBDevelopService.GetRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Save, null, options, request);
      }
      /// <summary>
      ///保存
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::DBDevelopService.BoolResultReplay> SaveAsync(global::DBDevelopService.GetRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SaveAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///保存
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::DBDevelopService.BoolResultReplay> SaveAsync(global::DBDevelopService.GetRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Save, null, options, request);
      }
      /// <summary>
      ///撤销
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::DBDevelopService.BoolResultReplay Cancel(global::DBDevelopService.GetRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Cancel(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///撤销
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::DBDevelopService.BoolResultReplay Cancel(global::DBDevelopService.GetRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Cancel, null, options, request);
      }
      /// <summary>
      ///撤销
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::DBDevelopService.BoolResultReplay> CancelAsync(global::DBDevelopService.GetRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CancelAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///撤销
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::DBDevelopService.BoolResultReplay> CancelAsync(global::DBDevelopService.GetRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Cancel, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override DevelopServerClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new DevelopServerClient(configuration);
      }
    }

  }
}
#endregion
